#+TITLE: The Wizard & The Fish
#+PROPERTY: header-args :cache yes
#+PROPERTY: header-args+ :mkdirp yes
#+PROPERTY: header-args+ :results silent
#+PROPERTY: header-args+ :padline no
* SONG 7.3

Once there was a Wizard so old and wise
that he asked Mother Night for a new enterprise
falling asleep his wish was heard
and by Merlin's beard
what a strange world he entered

In this world existed only zeros and ones
never had a Wizard seen such duality, not once
He approached one of the zeros and said
Who are you?
I'm a zero
yes, I see, but what do you do?
The zero said
I am the beginning and the end

Never had our Wizard met such a strange friend
He did not understand at all what he saw
and walking on this time met another strange fella
he approached the one and said:
Who are you?
I'm One
Yes, I see, but what do you do?
The one said: I am everything in between

The Wizard could not believe what his eyes had just seen
He sat down on a stone feeling tired and alone
missing his friends in the binary unknown
silent and sad he played with his beard
suddenly, a little fish appeared!

The Wizard said: you are not a zero or a one?
No, I'm a fish, come swim with me, come
They swam together and dived
deep into the ocean
until they found the place
where it once all began

The little fish took a small rake and starting raking the sand
and the Wizard was amazed by the waves of this new friend
he said
Little fish, who are you?
I'm a gardener, don't you see?
Well, yes, but what do you do?
The little fish - without stopping - calmly made clear
My task is important, this is what I do here,
the sand contains crucial information
which I need to order
before the rising of the sun.

Suddenly, from far, a big whale appeared
The Wizard, frightend, quickly hid behind his beard
The whale opened his mouth
but instead of swallowing our friend
released from his tongue
piles and piles of new sand.
The Wizard, startled, opened his mouth
but the fish said
No no no, no questions allowed,
we do not need to know where he comes from or goes
for a little mystery is what gives us purpose.

Finally something the Wizard could understand
he had found the mystery underneath the beginning and the end
he had dived way below everything in between
and saw the biggest whale he had ever seen

He said My dear fish, what you do, I can see,
is raking the maritime soil of mystery
from now on, I will protect you, your sand, and your shells,
coming back every year to update my spells.

They said their goodbyes
and the Wizard returned
to his nice and warm bed,
with all his lessons learned
He was happy that he now understood this strange place
and could protect his new friends for the rest of his days

* KSH
** PROFILE

#+BEGIN_SRC sh :tangle ~/.profile
  PATH=$HOME/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin
  PATH=$PATH:/usr/games:/usr/libexec:/usr/local/libexec:.
  ENV=$HOME/.kshrc
  export PATH HOME TERM HISTORY HISTSIZE ENV
#+END_SRC

** KSHRC

#+BEGIN_SRC sh :tangle ~/.kshrc
  HISTCONTROL=ignoredups:ignorespace
  HISTFILE=$HOME/.ksh_history
  HISTSIZE=4096
  
  if [ $(id -u) -eq 0 ]; then
      PS1='\[\e[1;31m\]\u@\h\[\e[1;33m\]:\[\e[1;35m\]\w\n\[\e[1;33m\]\$\[\e[m\] '
  else
      PS1='\[\e[1;32m\]\u@\h\[\e[1;33m\]:\[\e[1;35m\]\w\n\[\e[1;33m\]\$\[\e[m\] '
  fi

  alias cp='cp -i'
  alias df='df -h'
  alias du='du -h'
  alias e='emacs -nw'
  alias ec='emacsclient -c -a "" -nw'
  alias g='git'
  alias l='ls -a'
  alias ll='ls -lah'
  alias mv='mv -i'
  alias pg='pgrep -l'
  alias pingg='ping -c 4 openbsd.org'
  alias poweroff='doas shutdown -p now'
  alias reboot='doas shutdown -r now'
  alias rm='rm -i'
  tmux_create_or_attach () {
      [ -z "$TMUX" ] && \
          { tmux -q has-session && tmux attach -d || tmux -u; } || \
              { tmux new-session -d \; choose-tree -Zs; }
  }
  alias t='tmux_create_or_attach'
  alias x='startx'

  set -o emacs
  set -o csh-history

  stty kill  # fix backward kill in Emacs' ansi-term
#+END_SRC

* WSCONS

#+name: :tangle /doas::/etc/wsconsctl.conf
#+BEGIN_SRC conf
  keyboard.repeat.del1=200
  keyboard.repeat.deln=50
  keyboard.backlight=0
  mouse1.tp.tapping=1,3,2
  mouse1.tp.mtbuttons=1
  mouse1.reverse_scrolling=1
#+END_SRC

* XORG
** XDEFAULTS

#+NAME: Xdefaults
#+BEGIN_SRC conf :tangle ~/.Xdefaults
  XTerm*faceName: monospace:size=9
  XTerm*fullscreen: never
  XTerm*loginShell: true
  XTerm*metaSendsEscape: true
  XTerm*reverseVideo: true
  XTerm*scrollBar: false
  XTerm*selectToClipboard: true
  XTerm*termName: xterm-256color
#+END_SRC

#+BEGIN_SRC conf :noweb yes :tangle ~/.Xresources
  <<Xdefaults>>
#+END_SRC

** XENODM

#+name /etc/X11/xenodm/xenodm-config
#+BEGIN_SRC conf
  DisplayManager.*.autoLogin:     anon
#+END_SRC

** XSESSION

#+NAME: xsession
#+BEGIN_SRC conf :tangle ~/.xsession
  xset dpms 300 600 900 r rate 200 50
  xsetroot -solid black
  pixelclock &
  pixelbatt &
  sct 4000
  exec cwm
#+END_SRC

#+BEGIN_SRC conf :noweb yes :tangle ~/.xinitrc
  <<xsession>>
#+END_SRC

** CWM

#+BEGIN_SRC conf :tangle ~/.cwmrc
  borderwidth 1
  sticky yes
  snapdist 5
  moveamount 5
  fontname "monospace:bold:size=13"

  color activeborder '#B28'
  color inactiveborder '#627'
  color urgencyborder '#FF0'
  color menubg '#000'
  color menufg '#627'
  color font '#DDD'
  color selfont '#FFF'
  color font '#B28'

  unbind-key all
  bind-key 4-BackSpace restart
  bind-key 4C-BackSpace quit
  bind-key 4-Return 'xterm'
  bind-key 4C-Return 'chrome'
  bind-key 4-space menu-exec
  bind-key CS-w menu-window
  bind-key M-Tab window-cycle
  bind-key MS-Tab window-rcycle
  bind-key CS-q window-delete
  bind-key 4-m window-maximize
  bind-key CS-v window-vmaximize
  bind-key CS-h window-hmaximize
  bind-key 4C-m window-fullscreen
  bind-key 4-k window-move-up-big
  bind-key 4-j window-move-down-big
  bind-key 4-l window-move-right-big
  bind-key 4-h window-move-left-big
  bind-key 4C-k window-resize-up-big
  bind-key 4C-j window-resize-down-big
  bind-key 4C-l window-resize-right-big
  bind-key 4C-h window-resize-left-big
  unbind-mouse all
  bind-mouse R-1 menu-window
  bind-mouse M-1 window-move
  bind-mouse MS-1 window-resize
#+END_SRC
