#+TITLE: The Wizard & The Fish
#+PROPERTY: header-args :cache yes
#+PROPERTY: header-args+ :mkdirp yes
#+PROPERTY: header-args+ :padline no
#+PROPERTY: header-args+ :results silent
* SONG 7.3

Once there was a Wizard so old and wise
that he asked Mother Night for a new enterprise
falling asleep his wish was heard
and by Merlin's beard
what a strange world he entered

In this world existed only zeros and ones
never had a Wizard seen such duality, not once
He approached one of the zeros and said
Who are you?
I'm a zero
yes, I see, but what do you do?
The zero said
I am the beginning and the end

Never had our Wizard met such a strange friend
He did not understand at all what he saw
and walking on this time met another strange fella
he approached the one and said:
Who are you?
I'm One
Yes, I see, but what do you do?
The one said: I am everything in between

The Wizard could not believe what his eyes had just seen
He sat down on a stone feeling tired and alone
missing his friends in the binary unknown
silent and sad he played with his beard
suddenly, a little fish appeared!

The Wizard said: you are not a zero or a one?
No, I'm a fish, come swim with me, come
They swam together and dived
deep into the ocean
until they found the place
where it once all began

The little fish took a small rake and starting raking the sand
and the Wizard was amazed by the waves of this new friend
he said
Little fish, who are you?
I'm a gardener, don't you see?
Well, yes, but what do you do?
The little fish - without stopping - calmly made clear
My task is important, this is what I do here,
the sand contains crucial information
which I need to order
before the rising of the sun.

Suddenly, from far, a big whale appeared
The Wizard, frightend, quickly hid behind his beard
The whale opened his mouth
but instead of swallowing our friend
released from his tongue
piles and piles of new sand.
The Wizard, startled, opened his mouth
but the fish said
No no no, no questions allowed,
we do not need to know where he comes from or goes
for a little mystery is what gives us purpose.

Finally something the Wizard could understand
he had found the mystery underneath the beginning and the end
he had dived way below everything in between
and saw the biggest whale he had ever seen

He said My dear fish, what you do, I can see,
is raking the maritime soil of mystery
from now on, I will protect you, your sand, and your shells,
coming back every year to update my spells.

They said their goodbyes
and the Wizard returned
to his nice and warm bed,
with all his lessons learned
He was happy that he now understood this strange place
and could protect his new friends for the rest of his days

* KSH
** PROFILE

#+BEGIN_SRC sh :tangle ~/.profile
  PATH=$HOME/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin
  PATH=$PATH:/usr/games:/usr/libexec:/usr/local/libexec:.
  MANPATH=/usr/share/man:/usr/X11R6/man:/usr/local/man
  TERM=xterm-256color
  ENV=$HOME/.kshrc
  export PATH MANPATH HOME TERM ENV
#+END_SRC

** KSHRC

#+BEGIN_SRC sh :tangle ~/.kshrc
  HISTCONTROL=ignoredups:ignorespace
  HISTFILE=$HOME/.ksh_history
  HISTSIZE=4096
  export HISTORY HISTCONTROL HISTFILE HISTSIZE

  if [ $(id -u) -eq 0 ]; then
      PS1='\[\e[1;31m\]\u@\h\[\e[1;33m\]:\[\e[1;35m\]\w\n\[\e[1;33m\]\$\[\e[m\] '
  else
      PS1='\[\e[1;32m\]\u@\h\[\e[1;33m\]:\[\e[1;35m\]\w\n\[\e[1;33m\]\$\[\e[m\] '
  fi

  alias cp='cp -i'
  alias df='df -h'
  alias du='du -h'
  alias e='emacs -nw'
  alias ec='emacsclient -c -a "" -nw'
  alias g='git'
  alias l='ls -a'
  alias ll='ls -lah'
  alias mv='mv -i'
  alias pg='pgrep -l'
  alias pingg='ping -c 4 openbsd.org'
  alias bye='doas shutdown -p now'
  alias rb='doas shutdown -r now'
  alias rm='rm -i'
  t() {
      [ -z "$TMUX" ] && \
	  { tmux -q has-session && tmux attach -d || tmux -u; } || \
	      { tmux new-session -d \; choose-tree -Zs; }
  }
  alias x='startx'

  set -A complete_g -- $(git --list-cmds=main)
  set -o emacs
  set -o csh-history

  stty kill  # fix backward kill in Emacs' ansi-term
#+END_SRC

* WSCONS

#+name: :tangle (if (string-search "Lenovo" (shell-command-to-string "sysctl -n hw.vendor")) "/doas::/etc/wsconsctl.conf" "no")
#+begin_src conf
  keyboard.repeat.del1=200
  keyboard.repeat.deln=50
  keyboard.backlight=0
  mouse1.tp.mtbuttons=1
  mouse1.reverse_scrolling=1
  keyboard.map+="keycode 1   = Cmd_Debugger Caps_Lock"
  keyboard.map+="keycode 58  = Cmd_Debugger Escape"
  keyboard.map+="keycode 170 = Cmd Alt_L"      # Print_Screen
  keyboard.map+="keycode 183 = Cmd Alt_L"      # Print_Screen
  keyboard.map+="keycode 219 = Cmd Alt_L"      # Meta_L
  keyboard.map+="keycode 56  = Cmd Control_L"  # Cmd2 Alt_L
  keyboard.map+="keycode 184 = Cmd Control_R"  # Cmd2 Alt_R Multi_key
  keyboard.map+="keycode 29  = Cmd Meta_L"     # Cmd2 Alt_R Multi_key
  keyboard.map+="keycode 157 = Cmd Meta_R"     # Cmd2 Alt_R Multi_key
#+end_src

#+name: :tangle (if (string-search "Apple" (shell-command-to-string "sysctl -n hw.vendor")) "/doas::/etc/wsconsctl.conf" "no")
#+begin_src conf
  keyboard.backlight=0		# change keyboard backlight
  keyboard1.repeat.del1=200	# change keyboard repeat/delay
  keyboard1.repeat.deln=50
  keyboard1.encoding=us.metaesc	# use different keyboard encoding
  mouse1.tp.mtbuttons=1		# enable button clicking with multiple fingers
  mouse1.reverse_scrolling=1	# enable so-called "natural" scrolling
  keyboard1.map+="keysym Meta_L = Control_L"
  keyboard1.map+="keysym Meta_R = Control_R"
  keyboard1.map+="keysym Caps_Lock = Escape"
#+end_src

* XORG
** XDEFAULTS

#+BEGIN_SRC conf :tangle ~/.Xdefaults
  Xft.dpi: 96
  Xft.antialias: true
  XIdle.timeout: 300
  XLock.mode: random
  XLock.program: /usr/games/fortune -o
  XTerm*faceName: monospace:size=12
  XTerm*fullscreen: never
  XTerm*loginShell: true
  XTerm*metaSendsEscape: true
  XTerm*reverseVideo: true
  XTerm*scrollBar: false
  XTerm*selectToClipboard: true
  XTerm*termName: xterm-256color
#+END_SRC

** XENODM

#+name /etc/X11/xenodm/xenodm-config
#+BEGIN_SRC conf
  DisplayManager.*.autoLogin:     anon
#+END_SRC

** XMODMAP

#+begin_src conf :tangle (if (string-search "Lenovo" (shell-command-to-string "sysctl -n hw.vendor")) "~/.Xmodmap" "no")
  clear control
  clear mod1
  clear mod4
  clear mod5
  clear lock

  ! ThinkPad Chicklet Space Cadet
  keycode 64 = Control_L
  keycode 113 = Control_R
  keycode 115 = Alt_L Meta_L
  keycode 111 = Alt_R Meta_R
  keycode 37 = Super_L
  keycode 109 = Super_R

  keycode 9 = Caps_Lock
  keycode 66 = Escape

  add lock = Caps_Lock
  add Control = Control_L Control_R
  add mod1 = Alt_L Alt_R Meta_L Meta_R
  add mod4 = Super_L Super_R
#+end_src

** XSESSION

#+begin_src conf :tangle (if (string-search "Lenovo" (shell-command-to-string "sysctl -n hw.vendor")) "~/.xsession" "no")
  xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1
  xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2
  xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5
  xmodmap ~/.Xmodmap
#+end_src

#+begin_src conf :tangle (if (string-search "Apple" (shell-command-to-string "sysctl -n hw.vendor")) "~/.xsession" "no")
  setxkbmap -option 'caps:swapescape,ctrl:swap_lwin_lctl,ctrl:swap_rwin_rctl'
  xmodmap -e "keysym Left = Super_R"
#+end_src

#+begin_src conf :tangle ~/.xsession
  xset dpms 300 600 900 r rate 200 50
  xsetroot -solid black
  pixelclock &
  pixelbatt &
  saltab &
  sct 4000
  exec cwm
#+end_src

** CWM

#+BEGIN_SRC conf :tangle ~/.cwmrc
  borderwidth 1
  sticky yes
  snapdist 5
  moveamount 5
  fontname "monospace:bold:size=13"

  color activeborder '#B28'
  color inactiveborder '#627'
  color urgencyborder '#FF0'
  color menubg '#000'
  color menufg '#505'
  color font '#DDD'
  color selfont '#FFF'

  unbind-key all
  bind-key 4-BackSpace restart
  bind-key 4C-BackSpace quit

  bind-key 4-b firefox
  bind-key 4-e 'xterm -e emacsclient -c -a ""'
  bind-key 4-t terminal

  bind-key 4-v window-vtile
  bind-key 4C-v window-htile
  bind-key 4-q window-delete
  bind-key 4-m window-maximize
  bind-key 4-f window-fullscreen
  bind-key 4-k window-move-up-big
  bind-key 4-j window-move-down-big
  bind-key 4-l window-move-right-big
  bind-key 4-h window-move-left-big
  bind-key 4C-k window-resize-up-big
  bind-key 4C-j window-resize-down-big
  bind-key 4C-l window-resize-right-big
  bind-key 4C-h window-resize-left-big
  bind-key 4M-h window-snap-left
  bind-key 4M-j window-snap-down
  bind-key 4M-k window-snap-up
  bind-key 4M-l window-snap-right
  bind-key M-Escape window-cycle
  bind-key MS-Escape window-rcycle
  bind-key C-Escape window-cycle-ingroup
  bind-key CS-Escape window-rcycle-ingroup
  bind-key C-grave window-cycle-inclass
  bind-key CS-grave window-rcycle-inclass

  bind-key 4-a menu-cmd
  bind-key 4-s menu-ssh
  bind-key 4-space menu-exec
  bind-key 4C-space menu-exec-wm
  bind-key 4-g menu-group
  bind-key 4-w menu-window
  bind-key 4C-w menu-window-hidden

  bind-key 4-1 group-only-1
  bind-key 4-2 group-only-2
  bind-key 4-3 group-only-3
  bind-key 4-4 group-only-4
  bind-key 4-5 group-only-5
  bind-key 4-6 group-only-6
  bind-key 4-7 group-only-7
  bind-key 4-8 group-only-8
  bind-key 4-9 group-only-9

  bind-key 4S-1 group-toggle-1
  bind-key 4S-2 group-toggle-2
  bind-key 4S-3 group-toggle-3
  bind-key 4S-4 group-toggle-4
  bind-key 4S-5 group-toggle-5
  bind-key 4S-6 group-toggle-6
  bind-key 4S-7 group-toggle-7
  bind-key 4S-8 group-toggle-8
  bind-key 4S-9 group-toggle-9

  bind-key 4C-1 window-movetogroup-1
  bind-key 4C-2 window-movetogroup-2
  bind-key 4C-3 window-movetogroup-3
  bind-key 4C-4 window-movetogroup-4
  bind-key 4C-5 window-movetogroup-5
  bind-key 4C-6 window-movetogroup-6
  bind-key 4C-7 window-movetogroup-7
  bind-key 4C-8 window-movetogroup-8
  bind-key 4C-9 window-movetogroup-9

  bind-key 4-0 group-toggle-all
  bind-key 4C-0 window-group

  bind-key 4-Escape group-last
  bind-key 4-Tab group-cycle
  bind-key 4S-Tab group-rcycle

  unbind-mouse all
  bind-mouse M-1 window-move
  bind-mouse M-2 window-group
  bind-mouse M-3 window-resize
  bind-mouse M-4 window-lower
  bind-mouse M-5 window-raise
  bind-mouse R-1 menu-window
  bind-mouse R-2 menu-window-hidden
  bind-mouse R-3 menu-cmd
  bind-mouse R-4 group-cycle
  bind-mouse R-5 group-rcycle

  command 'chrome' chrome
  command 'firefox' firefox
  command 'emacs' 'xterm -e emacsclient -c -a ""'
  command 'xterm' terminal
  command 'xlock' xlock
  command 'sleep' zzz
  command 'reboot' 'shutdown -r now'
  command 'shutdown' 'shutdown -p now'
#+END_SRC

** GTK

#+NAME: gtk2
#+BEGIN_SRC conf :tangle ~/.gtkrc-2.0.mine
  gtk-key-theme-name = "Emacs"
#+END_SRC

#+BEGIN_SRC conf :noweb yes :tangle ~/.gtkrc-2.0
  <<gtk2>>
#+END_SRC

#+NAME: gtk3
#+BEGIN_SRC conf :tangle ~/.config/gtk-3.0/settings.ini
  [Settings]
  gtk-key-theme-name = Emacs
#+END_SRC
