#+TITLE: The Wizard & The Fish
#+PROPERTY: header-args :cache yes
#+PROPERTY: header-args+ :mkdirp yes
#+PROPERTY: header-args+ :padline no
#+PROPERTY: header-args+ :results silent
* SONG

Once there was a Wizard so old and wise
that he asked Mother Night for a new enterprise
falling asleep his wish was heard
and by Merlin's beard
what a strange world he entered

In this world existed only zeros and ones
never had a Wizard seen such duality, not once
He approached one of the zeros and said
Who are you?
I'm a zero
yes, I see, but what do you do?
The zero said
I am the beginning and the end

Never had our Wizard met such a strange friend
He did not understand at all what he saw
and walking on this time met another strange fella
he approached the one and said:
Who are you?
I'm One
Yes, I see, but what do you do?
The one said: I am everything in between

The Wizard could not believe what his eyes had just seen
He sat down on a stone feeling tired and alone
missing his friends in the binary unknown
silent and sad he played with his beard
suddenly, a little fish appeared!

The Wizard said: you are not a zero or a one?
No, I'm a fish, come swim with me, come
They swam together and dived
deep into the ocean
until they found the place
where it once all began

The little fish took a small rake and starting raking the sand
and the Wizard was amazed by the waves of this new friend
he said
Little fish, who are you?
I'm a gardener, don't you see?
Well, yes, but what do you do?
The little fish - without stopping - calmly made clear
My task is important, this is what I do here,
the sand contains crucial information
which I need to order
before the rising of the sun.

Suddenly, from far, a big whale appeared
The Wizard, frightend, quickly hid behind his beard
The whale opened his mouth
but instead of swallowing our friend
released from his tongue
piles and piles of new sand.
The Wizard, startled, opened his mouth
but the fish said
No no no, no questions allowed,
we do not need to know where he comes from or goes
for a little mystery is what gives us purpose.

Finally something the Wizard could understand
he had found the mystery underneath the beginning and the end
he had dived way below everything in between
and saw the biggest whale he had ever seen

He said My dear fish, what you do, I can see,
is raking the maritime soil of mystery
from now on, I will protect you, your sand, and your shells,
coming back every year to update my spells.

They said their goodbyes
and the Wizard returned
to his nice and warm bed,
with all his lessons learned
He was happy that he now understood this strange place
and could protect his new friends for the rest of his days

* KSH
#+BEGIN_SRC sh :tangle ~/.profile
  PATH=$HOME/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin
  PATH=$PATH:/usr/games:/usr/libexec:/usr/local/libexec:.
  MANPATH=/usr/share/man:/usr/X11R6/man:/usr/local/man
  TERM=xterm-256color
  ENV=$HOME/.kshrc
  export PATH MANPATH HOME TERM ENV
#+END_SRC
#+BEGIN_SRC sh :tangle ~/.kshrc
  HISTCONTROL=ignoredups:ignorespace
  HISTFILE=$HOME/.ksh_history
  HISTSIZE=4096
  export HISTORY HISTCONTROL HISTFILE HISTSIZE

  if [ $(id -u) -eq 0 ]; then
      PS1='\[\e[1;31m\]\u@\h\[\e[1;33m\]:\[\e[1;35m\]\w\n\[\e[1;33m\]\$\[\e[m\] '
  else
      PS1='\[\e[1;32m\]\u@\h\[\e[1;33m\]:\[\e[1;35m\]\w\n\[\e[1;33m\]\$\[\e[m\] '
  fi

  [ -f $HOME/.alias ] && . $HOME/.alias

  set -A complete_g -- $(git --list-cmds=main)
  set -o emacs
  set -o csh-history

  stty kill  # fix backward kill in Emacs' ansi-term

  [[ -n $INSIDE_EMACS ]] && cd() {
  	builtin cd "$@" && { echo '\032/\c'; pwd; } >/dev/tty
      }
#+END_SRC

* CRON

#+begin_src sh :tangle /doas::/etc/crontab
  SHELL=/bin/sh
  PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
  ,*	*	*	*	*	root	fscksaver > /dev/null
#+end_src

Shutdown when battery is lower than 10% and we're not charging.

#+begin_src shell :tangle /doas::/usr/local/bin/fscksaver :tangle-mode o755
  #!/bin/sh
  battery_percent=$(apm -l)
  ac_status=$(apm -a)
  if [ "$battery_percent" -lt 5 ] && [ "$ac_status" -eq 0 ]; then
      logger -t fscksaver "$battery_life% & not charging. Shutting down..."
      shutdown -p now
  fi
#+end_src

* WSCONS

#+begin_src conf :tangle (if (lenovo-p) "/doas::/etc/wsconsctl.conf" "no")
  keyboard.backlight=0
  keyboard.encoding=us.metaesc

  keyboard.map+="keycode 1   = Cmd_Debugger Caps_Lock"
  keyboard.map+="keycode 58  = Cmd_Debugger Escape"
  keyboard.map+="keycode 170 = Cmd Alt_L"      # Print_Screen
  keyboard.map+="keycode 183 = Cmd Alt_L"      # Print_Screen
  keyboard.map+="keycode 219 = Cmd Alt_L"      # Meta_L
  keyboard.map+="keycode 56  = Cmd Control_L"  # Cmd2 Alt_L
  keyboard.map+="keycode 184 = Cmd Control_R"  # Cmd2 Alt_R Multi_key
  keyboard.map+="keycode 29  = Cmd Meta_L"     # Cmd2 Alt_R Multi_key
  keyboard.map+="keycode 157 = Cmd Meta_R"     # Cmd2 Alt_R Multi_key
  keyboard.repeat.del1=200
  keyboard.repeat.deln=50

  mouse.tp.disable=1
  # mouse.tp.mtbuttons=1
  # mouse.reverse_scrolling=1
#+end_src

#+begin_src conf :tangle (if (apple-p) "/doas::/etc/wsconsctl.conf" "no")
  keyboard.backlight=0		# change keyboard backlight
  keyboard1.repeat.del1=200	# change keyboard repeat/delay
  keyboard1.repeat.deln=50
  keyboard1.encoding=us.metaesc	# use different keyboard encoding
  mouse1.tp.mtbuttons=1		# enable button clicking with multiple fingers
  mouse1.reverse_scrolling=1	# enable so-called "natural" scrolling
  keyboard1.map+="keysym Meta_L = Control_L"
  keyboard1.map+="keysym Meta_R = Control_R"
  keyboard1.map+="keysym Caps_Lock = Escape"
#+end_src

* XORG
** XENODM

#+BEGIN_SRC conf :tangle /doas::/etc/X11/xenodm/xenodm-config
  ! $OpenBSD: xenodm-config.in,v 1.6 2025/11/16 18:33:14 matthieu Exp $
  !
  DisplayManager.authDir:		/etc/X11/xenodm
  DisplayManager.errorLogFile:	/var/log/xenodm.log
  DisplayManager.servers:		/etc/X11/xenodm/Xservers
  DisplayManager*resources:	/etc/X11/xenodm/Xresources
  ! All displays should use authorization, but we cannot be sure
  ! X terminals may not be configured that way, so they will require
  ! individual resource settings.
  DisplayManager*authorize:	true
  !
  DisplayManager*startup:		/etc/X11/xenodm/Xstartup
  DisplayManager*session:		/etc/X11/xenodm/Xsession
  DisplayManager*reset:		/etc/X11/xenodm/Xreset
  DisplayManager*authComplain:	true
  ! The following three resources set up display :0 as the console.
  DisplayManager._0.setup:	/etc/X11/xenodm/Xsetup_0
  DisplayManager._0.startup:	/etc/X11/xenodm/GiveConsole
  DisplayManager._0.reset:	/etc/X11/xenodm/TakeConsole

  DisplayManager.*.authName:	MIT-MAGIC-COOKIE-1
  DisplayManager.*.autoLogin:     oxff

  ! Set by setusercontext(); don't reset it
  DisplayManager.exportList:	XDG_RUNTIME_DIR
#+END_SRC
