#+TITLE: TANGLE ALL THE THINGS!
#+AUTHOR: Toby Slight

#+PROPERTY: header-args :cache yes
#+PROPERTY: header-args+ :mkdirp yes
#+PROPERTY: header-args+ :padline no
#+PROPERTY: header-args+ :results silent
#+PROPERTY: header-args+ :tangle ~/.emacs.d/site-lisp/my-tangles.el
#+PROPERTY: header-args+ :tangle-mode (identity #o600)

#+OPTIONS: toc:t

To install this Emacs configuration we need to evaluate this buffer with:

=org-babel-execute-buffer= /(C-c C-v b)/

Then run the following newly defined function:

=my/tangle-directory= with  =execute-extended-command= /(M-x)/

You will be prompted to enter a directory. All org mode files in the entered
directory will be tangled.

Since we are visiting this file in the emacs configuration directory, we simply
need to press enter and all our emacs configuration org files will be tangled,
compiled and loaded.

/Alternatively, simply running [[file:../tangle.sh][tangle.sh]] from a terminal should do all of the
above, automagically, without even having to open Emacs.../

* CONTENTS                                                         :TOC_5_gh:
- [[#babel-no-confirm][BABEL NO CONFIRM]]
- [[#variables][VARIABLES]]
- [[#os-config-directory][OS CONFIG DIRECTORY]]
- [[#insert-boilerplate][INSERT BOILERPLATE]]
- [[#compile-and-load-config][COMPILE AND LOAD CONFIG]]
- [[#tangle-directory][TANGLE DIRECTORY]]
- [[#tangle-all][TANGLE ALL]]
- [[#parent-directories][PARENT DIRECTORIES]]
- [[#auto-tangle][AUTO TANGLE]]
- [[#hardware-tangle][HARDWARE TANGLE]]
- [[#os-tangle][OS TANGLE]]

* BABEL NO CONFIRM

Turn off evaluation confirmation so we can execute all the src blocks
in the buffer with =org-babel-execute-buffer= /C-c C-v b/.

We will turn this back on later in org-modes package configuration,
since I'd rather not let org babel execute arbitrary code without
confirmation.

[[https://www.reddit.com/r/emacs/comments/64jhlt/autoexecuting_code_in_org_mode/%5D%5D][Autoexecuting code in org mode]]

[[https://emacs.stackexchange.com/questions/2945/org-babel-eval-with-no-confirmation-is-explicit-eval-yes%5D%5D][Org Babel eval with no confirmation]]

#+Begin_SRC emacs-lisp
  (setq org-confirm-babel-evaluate nil)
#+END_SRC

* VARIABLES

#+BEGIN_SRC emacs-lisp
  (setq-default buffer-file-coding-system 'utf-8-unix)
  (setq my/config-directory "~/etc/"
        my/agnostic-config-directory (concat my/config-directory "agnostic/")
        my/emacs-config-directory (concat my/config-directory "emacs/"))
#+END_SRC

* OS CONFIG DIRECTORY

#+BEGIN_SRC emacs-lisp
  (defun my/os-config-directory ()
    (car (remove nil
                 (mapcar (lambda (d)
                           (if (and (file-directory-p d)
                                    (string-match
                                     (file-name-base d) system-configuration))
                               d))
                         (directory-files my/config-directory t "^[^\\..]*$")))))
#+END_SRC

* INSERT BOILERPLATE

#+BEGIN_QUOTE
To enable lexical binding in your elisp library, put a line like this
at the top of the file:

=;; -*- lexical-binding: t -*-=

This will enable lexical-binding for the code in the file, but note
that global variables declared with defvar, defcustom or defconst will
be dynamically bound due to the global binding being marked as
“special” by those forms.

-- [[https://www.emacswiki.org/emacs/dynamicbindingvslexicalbinding][emacs wiki - dynamic vs lexical binding]]
-- [[https://www.emacswiki.org/emacs/lexicalbinding][emacs wiki - lexical binding]]
#+END_QUOTE

Take a file as an argument & insert elisp header and footer comments
into it if it's an elisp file.

If the file is in my site-lisp directory also insert a provide
expression, so that the file can be loaded as a package.

Return the file name, so that this function can be piped to other
functions, such as my/compile-and-load-file.

[[http://ergoemacs.org/emacs/elisp_buffer_file_functions.html][Ergoemacs Buffer File Functions]]
[[https://superuser.com/questions/297774/how-do-i-get-emacs-to-insert-text-into-an-arbitrary-file][Superuser - How to insert text into a file]]

#+BEGIN_SRC emacs-lisp
  (defun my/insert-boilerplate (&optional file)
    "Take a FILE as an argument & insert elisp header and footer
  comments into it, if it's an elisp FILE.

  If the file is in my site-lisp directory also insert a provide
  expression, so that the FILE can be loaded as a package.

  Return the file name, so that this function can be piped to other
  functions, such as my/compile-and-load-file."
    (when file
      (when (equal (file-name-extension file) "el")
        (let ((temp-buffer (set-buffer (find-file-noselect file))))
          (when temp-buffer
            (unwind-protect
                (progn
                  (goto-char (point-min))
                  (insert ";; -*- lexical-binding: t; -*-\n")
                  (goto-char (point-max))
                  (let ((provide-string (file-name-sans-extension
                                         (file-name-nondirectory file))))
                    (insert (concat "(provide '"provide-string")")))
                  (message (concat "Inserted boilerplate into " file)))
              (save-buffer temp-buffer)
              (kill-buffer temp-buffer))))
        (message (concat "Cleaning up " file"~ backup file..."))
        (when (file-readable-p (concat file "~"))
          (delete-file (concat file "~"))
          (message (concat "Deleted " file "~ backup file"))))
      file))
#+END_SRC

* COMPILE AND LOAD CONFIG

Byte compile init file and site-lisp directory and then load the newly
compiled configuration.

#+BEGIN_SRC emacs-lisp
  (defun my/compile-and-load-config ()
    "Byte compile init file and site-lisp directory and then load
     the newly compiled configuration."
    (interactive)
    (byte-compile-file (concat user-emacs-directory "init.el") 0)
    (byte-compile-file (concat user-emacs-directory "my-packages.el") 0)
    (byte-recompile-directory (concat user-emacs-directory "site-lisp") 0))
#+END_SRC

* TANGLE DIRECTORY

[[http://fgiasson.com/blog/index.php/2016/10/26/literate-clojure-programming-tangle-all-in-org-mode/][Frederick Giasson's Literate Programming Blog]]

[[https://www.gnu.org/software/emacs/manual/html_node/eintr/print_002delements_002dof_002dlist.html][Gnu Emacs Manual - Print elements of a list]]

[[https://www.gnu.org/software/emacs/manual/html_node/elisp/Mapping-Functions.html][Gnu Emacs Manual - Mapping Functions]]

[[http://ergoemacs.org/emacs/elisp_mapcar_loop.html][Ergoemacs mapcar]]

Takes a DIRECTORY as an argument and recursively tangles all the
org-mode files in it and it's child directories

If the directory being tangled is my emacs configuration directory,
run [[*COMPILE%20AND%20LOAD%20CONFIG][my/compile-and-load-config]].

#+BEGIN_SRC emacs-lisp
  (defun my/tangle-directory (directory)
    "Takes a DIRECTORY as an argument and recursively tangles all
  the org-mode files in it and it's child directories.

  If the directory being tangled is my emacs configuration
  directory, run my/compile-and-load-config."
    (interactive "DDirectory: ")

    (unless (featurep 'org) (require 'org)) ; needed for bootstrap

    (mapc (lambda (file)
            (my/insert-boilerplate
             (format "%s" (car (org-babel-tangle-file file)))))
          (directory-files-recursively directory ".*\\.org$"))

    (when (equal (expand-file-name directory)
                 (expand-file-name my/emacs-config-directory))
      (my/compile-and-load-config)
      (mapc (lambda (file)
            (if (not (file-directory-p file))
                (delete-file file)))
              (directory-files (getenv "HOME") t "^\\.emacs.*")))

    (message (concat "my/tangle-directory "directory" completed.")))
#+END_SRC

* TANGLE ALL

#+BEGIN_SRC emacs-lisp
  (defun my/tangle-all ()
    (interactive)
    (my/tangle-directory my/agnostic-config-directory)
    (my/tangle-directory my/emacs-config-directory)
    (my/tangle-directory (my/os-config-directory))
    (message "Tangled all the things!"))
#+END_SRC

* PARENT DIRECTORIES

#+BEGIN_SRC emacs-lisp
  (defun my/parent-directory-name (file)
    (file-name-nondirectory
     (directory-file-name
      (file-name-directory file))))

  (defun my/parent-directory-path (file)
    (string-match "\\(.*\\)/" file)
    (match-string 1 file))
#+END_SRC

* AUTO TANGLE

Automatically tangle files in the directories specified below when
they are edited. Providing the system-type value is correct.

It doesn't make sense to tangle openbsd configurations files on to a
linux box, for example.

However, I may want to be able to edit them without auto tangling from
another OS.

#+BEGIN_SRC emacs-lisp
  (defun my/auto-tangle ()
    "Auto tangle files in the directories specified below when
  they are edited. Providing the system-type value is

  It doesn't make sense to tangle openbsd configurations files on
  to a linux box, for example.

  However, I may want to be able to edit them without auto tangling
  from another OS."
    (let ((current-directory-path
           (file-name-directory (directory-file-name buffer-file-name))))
      (cond ((string-prefix-p
              (expand-file-name my/emacs-config-directory)
              current-directory-path)
             (byte-compile-file
              (my/insert-boilerplate
               (expand-file-name (car (org-babel-tangle))))
              0))
            ((or (string-prefix-p
                  (expand-file-name my/agnostic-config-directory)
                  current-directory-path)
                 (string-prefix-p
                  (my/os-config-directory)
                  current-directory-path))
             (org-babel-tangle)))))
#+END_SRC

* HARDWARE TANGLE

Tangle block to PATH if VENDOR string matches that in
/sys/class/dmi/id/chassis_vendor.

Inspired by https://emacs.stackexchange.com/a/14034

#+BEGIN_SRC emacs-lisp
  (defun my/hardware-tangle (vendor file path)
    "Tangle block to PATH if VENDOR string matches the relevant FILE in
      /sys/class/dmi/id/."
    (if (string-match vendor
                      (with-temp-buffer
                        (insert-file-contents (concat "/sys/class/dmi/id/" file))
                        (buffer-string)))
        path
      "no"))
#+END_SRC

* OS TANGLE

Inspired by https://emacs.stackexchange.com/a/14034

#+BEGIN_SRC emacs-lisp
  (defun my/os-tangle (os)
    (when (not (equal system-type os)) "no"))
#+END_SRC
