* HACKS AND GLORY AWAIT!

#+BEGIN_QUOTE
Stumpwm is a "everything-and-the-kitchen-sink WM" or "the emacs of WMs."

StumpWM manages windows the way emacs manages buffers, or the way screen manages
terminals. If you want a flexible, customizable, hackable desktop experience,
look no further.

-- [[https://github.com/stumpwm/stumpwm][StumpWM GitHub]]
#+END_QUOTE

** PRE-REQUISITES

Get Quicklisp from [[https://www.quicklisp.org/beta/][here,]] and then load into the REPL with:

~$ sbcl --load quicklisp.lisp~

From the REPL, install it:

#+BEGIN_SRC common-lisp
  (quicklisp-quickstart:install)
#+END_SRC

And make sure you have added it to your lisp init file using:

#+BEGIN_SRC common-lisp
  (ql:add-to-init-file)
#+END_SRC

Install stumpwm and some packages we need for niceties.

#+BEGIN_SRC common-lisp
  (ql:quickload :stumpwm)                ;; Install stumpwm
  (ql:quickload :xembed)                 ;; Required by stumptray
  (ql:quickload :clx-truetype)           ;; Required by ttf-fonts
  (ql:quickload :swank)                  ;; Required by slime-connect
  (ql:quickload :quicklisp-slime-helper) ;; Required by slime-connect
#+END_SRC

Next, clone my fork of the [[https://github.com/tslight/stumpwm-contrib][stumpwm-contrib]] repository to ~$HOME/src~, to be able
use ttf-fonts, cycle-mru, sensors and stumptray.

Finally, we need to tangle the code in the files linked to below:

- [[file:init.org][Initialisation]]
- [[file:settings.org][Settings]]
- [[file:utils.org][Utilities]]
- [[file:keys.org][Keybindings]]

Please see the main [[file:../README.org][etc repo README]] for more details on Emacs tangling,
org-mode, literate programming and how I manage configuration files and such.

*N.B.* My more complex utilities are in my fork of [[https://github.com/tslight/stumpwm-contrib][stumpwm-contrib]]:

- [[https://github.com/tslight/stumpwm-contrib/tree/master/util/cycle-mru][cycle-mru]] gives me back glorious alt-tab behaviour.
- [[https://github.com/tslight/stumpwm-contrib/tree/master/modeline/sensors][sensors]] allows me to see just how hot my crotch is getting...

** INSPIRATIONS

https://dataswamp.org/~solene/2016-06-06-stumpwm.html

https://github.com/areina/stumpwm.d

https://github.com/stumpwm/stumpwm/wiki/Customize
