#+TITLE: LET'S GET THIS LISPARTY STARTED!
#+AUTHOR: Toby Slight

#+PROPERTY: header-args :cache yes
#+PROPERTY: header-args+ :mkdirp yes
#+PROPERTY: header-args+ :padline no
#+PROPERTY: header-args+ :results silent
#+PROPERTY: header-args+ :tangle ~/.emacs.d/init.el
#+PROPERTY: header-args+ :tangle-mode (identity #o600)

#+OPTIONS: toc:t

Please see the [[file:README.org][README]] and/or [[file:my-tangles.org][my-tangles.org]] for instructions on how to
install.

This initialisation file wraps our configuration in some speed hacks
found on the interwebs with let expressions.

It also sets the stage for John Wiegley's amazing [[https://github.com/jwiegley/use-package][use-package]] macro to
load the rest of the configuration files, additional packages and
modes.

* STARTUP SPEED TIPS

[[https://www.reddit.com/r/emacs/comments/3kqt6e/2_easy_little_known_steps_to_speed_up_emacs_start/][Reddit Thread on Startup Speed]]

*Doom Tricks:*

#+BEGIN_QUOTE
Doom employs a few techniques to achieve its speed (as well as a ton
of premature optimization). Here are some of its more important
secrets:

- The garbage collector eats up a lot of time during startup, so turn
  up its memory threshold to prevent it from getting triggered.

  Avoid garbage collection during startup. The GC eats up quite a bit
  of time, easily doubling startup time. The trick is to turn up the
  memory threshold to prevent it from running.

- Unrelated to GC, but I also temporarily unset
  file-name-handler-alist, which Emacs looks through every time it
  loads a file; this gives me a modest 90-120ms boost.

  Like we did with the garbage collector, unset
  file-name-handler-alist too (temporarily). Every file opened and
  loaded by Emacs will run through this list to check for a proper
  handler for the file, but during startup, it won’t need any of
  them. Doom doesn’t, at least.

- Every time you load or require a package, Emacs does an O(n) equal
  lookup on load-path. Little you can do about this, but where I can I
  let-bind load-path to a subset of itself (like in
  doom-initialize).

- I also use load! to load all of Doom's module files, which expands
  to (load ABSOLUTE_PATH nil t) without a load-path lookup.

- package.el initialization loads every package autoloads file and
  populates load-path. That makes (package-initialize) a great target
  for premature optimizers like me! Besides, i don't need those
  autoloads (I define them manually), so turn it off, and then I
  populate load-path manually.

- Lazy load everything. Packages are an obvious one; use-package
  defers 90% of Doom's packages at startup. Package checking isn't
  done either (as you've noticed, it's done externally), which is a
  large savings.

- Exploit byte-compilation. Many expensive things are cached, or even
  cut out, at compile time. I get a ~40% improvement in startup time
  with make compile-core. You can byte-compile the whole config with
  make compile but that takes much longer and you get significantly
  diminished returns.

- Use lexical-binding everywhere. Add ;; -*- lexical-binding: t; -*-
  to the top of your elisp files. This can cause code breakage if your
  code depends on dynamic variables, but I've written Doom not to.

- Avoid lambdas by preferring cl-loop or dolist over mapcar and
  mapc. Lambdas add a little overhead each time they're executed in
  loops (and the byte-compiler has trouble inlining them; especially
  when lexical-binding is on!).

-- [[https://github.com/hlissner/doom-emacs/wiki/FAQ#how-is-dooms-startup-so-fast][Doom Fast Startup Explanation from FAQ]]
-- [[https://github.com/hlissner/doom-emacs/issues/310][Doom Fast Startup Explanation from GitHub Issue]]
#+END_QUOTE

* MAGIC UNICORN SUMMONING SPELL

Wrap everything in a let expression that sets garbage collection
variables to extremely high values and unsets file-name-handler-list.

However, have them be restored once the init code has run, since let
only sets local variables.

Set up package.el, add melpa repository, add package autoloads, then
install [[https://github.com/jwiegley/use-package][use-package]], if it's not already.

Set some use-package variables, and then add our configuration file
directory to the [[help:load-path][load path]].

Finally [[help:require][require]] our package configuration, which calls use-package to
set everything else up.

#+BEGIN_SRC emacs-lisp
  (let ((file-name-handler-alist nil)
        (gc-cons-threshold most-positive-fixnum)
        (gc-cons-percentage 0.8))
    (require 'package)
    (setq package-enable-at-startup nil
          package--init-file-ensured t)
    (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
    (package-initialize)
    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))
    (require 'use-package)
    (setq use-package-enable-imenu-support t
          use-package-verbose t)
    (setq my/config-directory "~/etc/"
          my/site-lisp                 (concat user-emacs-directory "site-lisp/")
          my/agnostic-config-directory (concat my/config-directory "agnostic/")
          my/emacs-config-directory    (concat my/config-directory "emacs/")
          my/linux-config-directory    (concat my/config-directory "linux/")
          my/macos-config-directory    (concat my/config-directory "macos/")
          my/freebsd-config-directory  (concat my/config-directory "freebsd/")
          my/netbsd-config-directory   (concat my/config-directory "netbsd/")
          my/openbsd-config-directory  (concat my/config-directory "openbsd/")
          my/windows-config-directory  (concat my/config-directory "windows/"))
    (add-to-list 'load-path my/site-lisp)
    (require 'my-packages-minimal)
    (require 'my-packages-emacs)
    (when (display-graphic-p)
      (require 'my-packages-full))
    (require 'my-packages))
#+END_SRC

Please navigate to [[file:my-packages.org][my-packages]] to see how the rest of this
configuration falls into place...
