#+TITLE: UNICORN INARDS
#+AUTHOR: Toby Slight

#+PROPERTY: header-args :cache yes
#+PROPERTY: header-args+ :mkdirp yes
#+PROPERTY: header-args+ :padline no
#+PROPERTY: header-args+ :results silent
#+PROPERTY: header-args+ :tangle ~/.emacs.d/site-lisp/my-org.el
#+PROPERTY: header-args+ :tangle-mode (identity #o600)

#+OPTIONS: toc:t

Please see the [[file:README.org][README]] and/or [[file:my-tangles.org][my-tangles.org]] for instructions on how to
install.

* CONTENTS                                                         :TOC_5_gh:
- [[#recursive-sort][RECURSIVE SORT]]
- [[#tangle-block][TANGLE BLOCK]]
- [[#capture-templates][CAPTURE TEMPLATES]]
- [[#structure-templates][STRUCTURE TEMPLATES]]
- [[#packages][PACKAGES]]
   - [[#htmlize][HTMLIZE]]
   - [[#ox-latex][OX LATEX]]
   - [[#org-bullets][ORG BULLETS]]
   - [[#toc-org][TOC ORG]]

* RECURSIVE SORT

#+BEGIN_QUOTE
Sort entries on a certain level of an outline tree.

If there is an active region, the entries in the region are sorted.
Else, if the cursor is before the first entry, sort the top-level
items.  Else, the children of the entry at point are sorted.

Sorting can be alphabetically, numerically, by date/time as given by a
time stamp, by a property, by priority order, or by a custom function.

The command prompts for the sorting type unless it has been given to
the function through the SORTING-TYPE argument, which needs to be a
character, (?n ?N ?a ?A ?t ?T ?s ?S ?d ?D ?p ?P ?o ?O ?r ?R ?f ?F).
Here is the precise meaning of each character:

n) Numerically, by converting the beginning of the entry/item to a
   number.
a) Alphabetically, ignoring the TODO keyword and the priority, if any.
o) By order of TODO keywords.
t) By date/time, either the first active time stamp in the entry, or,
   if none exist, by the first inactive one.
s) By the scheduled date/time.
d) By deadline date/time.
c) By creation time, which is assumed to be the first inactive time
   stamp at the beginning of a line.
p) By priority according to the cookie.
r) By the value of a property.

Capital letters will reverse the sort order.

If the SORTING-TYPE is ?f or ?F, then GETKEY-FUNC specifies a function
to be called with point at the beginning of the record.  It must
return either a string or a number that should serve as the sorting
key for that record.

Comparing entries ignores case by default.  However, with an optional
argument WITH-CASE, the sorting considers case as well.

Sorting is done against the visible part of the headlines, it ignores
hidden links.

-- [[help:org-sort-entries][Help Page]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (defun my/org-recursive-sort ()
    "Sort all entries in the current buffer, recursively."
    (interactive)
    (org-map-entries
     (lambda ()
       (condition-case x
           (org-sort-entries nil ?a)
         (user-error)))))
#+END_SRC

* TANGLE BLOCK

#+BEGIN_QUOTE
Write code blocks to source-specific files.
Extract the bodies of all source code blocks from the current
file into their own source-specific files.
With one universal prefix argument, only tangle the block at point.
When two universal prefix arguments, only tangle blocks for the
tangle file of the block at point.
Optional argument TARGET-FILE can be used to specify a default
export file for all source blocks.  Optional argument LANG can be
used to limit the exported source code blocks by language.

-- [[help:org-babel-tangle][Help Page]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (defun my/org-tangle-block()
    "Only tangle the block at point."
    (interactive)
    (let ((current-prefix-arg '(4)))
      (call-interactively 'org-babel-tangle)))
#+END_SRC

* CAPTURE TEMPLATES

#+BEGIN_QUOTE
You can use templates for different types of capture items, and for
different target locations. The easiest way to create such templates
is through the customize interface.

Before we give the formal description of template definitions, let’s
look at an example. Say you would like to use one template to create
general TODO entries, and you want to put these entries under the
heading ‘Tasks’ in your file ~/org/gtd.org. Also, a date tree in the
file journal.org should capture journal entries. A possible
configuration would look like:

=(setq org-capture-templates
 '(("t" "Todo" entry (file+headline "~/org/gtd.org" "Tasks")
        "* TODO %?\n  %i\n  %a")
   ("j" "Journal" entry (file+olp+datetree "~/org/journal.org")
        "* %?\nEntered on %U\n  %i\n  %a")))=

During expansion of the template, %a has been replaced by a link to
the location from where you called the capture command. This can be
extremely useful for deriving tasks from emails, for example. You fill
in the task definition, press C-c C-c and Org returns you to the same
place where you started the capture process.

To define special keys to capture to a particular template without
going through the interactive template selection, you can create your
key binding like this:

=(define-key global-map "\C-cx"
   (lambda () (interactive) (org-capture nil "x")))=

-- [[https://orgmode.org/manual/Capture-templates.html][Worg Entry]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (setq org-capture-templates
        '(("t" "TODO Entry"
           entry (file+headline "~/org/todo.org" "CURRENT")
           "* TODO %?\n  %i\n  %a")
          ("j" "Journal Entry"
           entry (file+datetree "~/org/journal.org" "JOURNAL")
           "* %?\nEntered on %U\n  %i\n  %a")
          ("h" "Health Note"
           entry (file+headline "~/org/notes.org" "HEALTH")
           "* %?\n  %i\n  %a")
          ("m" "Misc Note"
           entry (file+headline "~/org/notes.org" "MISC")
           "* %?\n  %i\n  %a")
          ("M" "Mathematics Note"
           entry (file+headline "~/org/notes.org" "MATHEMATICS")
           "* %?\n  %i\n  %a")
          ("P" "Philosophy Note"
           entry (file+headline "~/org/notes.org" "PHILOSOPHY")
           "* %?\n  %i\n  %a")
          ("p" "Programming Note"
           entry (file+headline "~/org/notes.org" "PROGRAMMING")
           "* %?\n  %i\n  %a")
          ("s" "Sysadmin Note"
           entry (file+headline "~/org/notes.org" "SYSADMIN")
           "* %?\n  %i\n  %a")
          ("w" "Webadmin Note"
           entry (file+headline "~/org/notes.org" "WEBADMIN")
           "* %?\n  %i\n  %a")))
#+END_SRC
* STRUCTURE TEMPLATES
#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-structure-template-alist
               '("C" "#+BEGIN_SRC c\n?\n#+END_SRC"
                 "<src lang=\"c\">\n\n</src>"))
  (add-to-list 'org-structure-template-alist
               '("el" "#+BEGIN_SRC emacs-lisp\n?\n#+END_SRC"
                 "<src lang=\"emacs-lisp\">\n\n</src>"))
  (add-to-list 'org-structure-template-alist
               '("j" "#+BEGIN_SRC java\n?\n#+END_SRC"
                 "<src lang=\"java\">\n\n</src>"))
  (add-to-list 'org-structure-template-alist
               '("py" "#+BEGIN_SRC python\n?\n#+END_SRC"
                 "<src lang=\"python\">\n\n</src>"))
  (add-to-list 'org-structure-template-alist
               '("sh" "#+BEGIN_SRC sh\n?\n#+END_SRC"
                 "<src lang=\"sh\">\n\n</src>"))
#+END_SRC
* PACKAGES
** HTMLIZE
#+BEGIN_SRC emacs-lisp
  ;; source code syntax highlighting when html exporting
  (use-package htmlize
    :defer t
    :ensure t)
#+END_SRC
** OX LATEX
#+BEGIN_SRC emacs-lisp
  (use-package ox-latex
    :defer t
    :config
    (add-to-list 'org-latex-packages-alist '("" "minted"))
    (setq org-latex-listings 'minted)
    (setq org-latex-pdf-process
          '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
            "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
            "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f")))
#+END_SRC
** ORG BULLETS
#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
    :defer t
    :if window-system
    :ensure t
    :hook
    (org-mode . org-bullets-mode))
#+END_SRC
** TOC ORG

[[https://github.com/snosov1/toc-org][GitHub repo]]

#+BEGIN_SRC emacs-lisp
  (use-package toc-org
    :defer t
    :ensure t
    :hook
    (org-mode . toc-org-enable))
#+END_SRC
