#+TITLE: KITCHEN SINK PACKAGE CONFIGURATION
#+AUTHOR: Toby Slight

#+PROPERTY: header-args :cache yes
#+PROPERTY: header-args+ :mkdirp yes
#+PROPERTY: header-args+ :padline no
#+PROPERTY: header-args+ :results silent
#+PROPERTY: header-args+ :tangle ~/.emacs.d/site-lisp/my-packages-full.el
#+PROPERTY: header-args+ :tangle-mode (identity #o600)

#+OPTIONS: toc:t

Please see the [[file:README.org][README]] and/or [[file:my-tangles.org][my-tangles.org]] for instructions on how to
install.

All the non-essential, but nice to have stuff goes in here.


* CONTENTS                                                         :TOC_5_gh:
- [[#aggressive-indent][AGGRESSIVE INDENT]]
- [[#async][ASYNC]]
- [[#autohotkey-mode][AUTOHOTKEY MODE]]
- [[#avy][AVY]]
- [[#change-inner][CHANGE INNER]]
- [[#company-mode][COMPANY MODE]]
- [[#counsel-projectile][COUNSEL PROJECTILE]]
- [[#diminish][DIMINISH]]
- [[#emmet-mode][EMMET MODE]]
- [[#exec-path-from-shell][EXEC PATH FROM SHELL]]
- [[#expand-region][EXPAND REGION]]
- [[#flx][FLX]]
- [[#flycheck][FLYCHECK]]
- [[#git-timemachine][GIT TIMEMACHINE]]
- [[#hungry-delete][HUNGRY DELETE]]
- [[#iedit][IEDIT]]
- [[#lispy][LISPY]]
- [[#markdown][MARKDOWN]]
- [[#paredit][PAREDIT]]
- [[#pc-buffer-switch][PC BUFFER SWITCH]]
- [[#powerline][POWERLINE]]
- [[#powershell][POWERSHELL]]
- [[#projectile][PROJECTILE]]
- [[#python][PYTHON]]
   - [[#elpy][ELPY]]
   - [[#pep8][PEP8]]
   - [[#jedi][JEDI]]
   - [[#company-jedi][COMPANY JEDI]]
- [[#smex][SMEX]]
- [[#ssh-agency][SSH-AGENCY]]
- [[#web-mode][WEB MODE]]
- [[#wgrep][WGREP]]
- [[#which-key][WHICH KEY]]
- [[#yasnippets][YASNIPPETS]]

* AGGRESSIVE INDENT
#+BEGIN_SRC emacs-lisp :tangle no
  (use-package aggressive-indent
    :disabled t
    :ensure t
    :diminish aggressive-indent-mode
    :defer t
    :hook
    (prog-mode . aggressive-indent-mode))
#+END_SRC
* ASYNC
#+BEGIN_SRC emacs-lisp
  (use-package async
    :ensure t
    :defer t
    :config
    (async-bytecomp-package-mode 1)
    (dired-async-mode 1))
#+END_SRC
* AUTOHOTKEY MODE
#+BEGIN_SRC emacs-lisp
  (use-package ahk-mode
    :if (eq system-type 'windows-nt)
    :ensure t
    :mode "\\.ahk\\'")
#+END_SRC
* AVY
#+BEGIN_SRC emacs-lisp
  (use-package avy
    :after bind-key
    :ensure t
    :bind
    ("C-c j j" . avy-goto-char)
    ("C-c j c" . avy-goto-char-2)
    ("C-c j l" . avy-goto-line)
    ("M-g l" . avy-goto-line)
    ("M-g w" . avy-goto-word-0)
    ("C-c j w" . avy-goto-word-0)
    ("C-c j W" . avy-goto-word-1)
    :config
    (setq avy-dispatch-alist '((?c . avy-action-copy)
                               (?k . avy-action-kill-move)
                               (?K . avy-action-kill-stay)
                               (?m . avy-action-mark)
                               (?z . avy-action-zap-to-char))))
#+END_SRC
* CHANGE INNER
#+BEGIN_QUOTE
change-inner gives you vim's ci command, building on expand-region. It
is most easily explained by example:

=function test() { return "semantic kill";}=

With point after the word semantic

change-inner " would kill the contents of the string
change-outer " would kill the entire string
change-inner { would kill the return-statement
change-outer { would kill the entire block

I use M-i and M-o for this.

Giving these commands a prefix argument C-u means copy instead of
kill.

-- [[https://github.com/magnars/change-inner.el][GitHub Repo]]
#+END_QUOTE
#+BEGIN_SRC emacs-lisp
  (use-package change-inner
    :ensure t
    :bind
    ("M-i" . change-inner)
    ("M-o" . change-outer))
#+END_SRC
* COMPANY MODE
#+BEGIN_SRC emacs-lisp
  (use-package company
    :ensure t
    :defer t
    :diminish company-mode
    :hook
    (prog-mode . company-mode))
#+END_SRC
* COUNSEL PROJECTILE
#+BEGIN_SRC emacs-lisp
  (use-package counsel-projectile
    :ensure t
    :defer t
    :after (counsel projectile)
    :config
    (counsel-projectile-mode))
#+END_SRC
* DIMINISH
#+BEGIN_SRC emacs-lisp
  (use-package diminish
    :defer 4
    :ensure t)
#+END_SRC
* EMMET MODE
#+BEGIN_SRC emacs-lisp
  (use-package emmet-mode
    :defer t
    :ensure t
    :diminish
    :after web-mode
    :hook
    (sgml-mode)
    (html-mode)
    (css-mode)
    (web-mode))
#+END_SRC

* EXEC PATH FROM SHELL

https://github.com/purcell/exec-path-from-shell

#+BEGIN_SRC emacs-lisp
  (use-package exec-path-from-shell
    :if (eq system-type 'darwin)
    :ensure t
    :init
    (exec-path-from-shell-initialize))
#+END_SRC

* EXPAND REGION
#+BEGIN_SRC emacs-lisp
  (use-package expand-region
    :ensure t
    :bind
    ("C-S-<SPC>" . er/expand-region)
    ("C-=" . er/expand-region))
#+END_SRC
* FLX
#+BEGIN_SRC emacs-lisp
  (use-package flx
    :defer t
    :ensure t
    :after (counsel ivy))
#+END_SRC
* FLYCHECK
#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :ensure t
    :defer t
    :diminish flycheck-mode
    :hook
    (prog-mode . flycheck-mode))
#+END_SRC
* GIT TIMEMACHINE

[[https://github.com/pidu/git-timemachine][GitHub Repo]]

#+BEGIN_SRC emacs-lisp
  (use-package git-timemachine
    :defer t
    :ensure t)
#+END_SRC
* HUNGRY DELETE
#+BEGIN_SRC emacs-lisp
  (use-package hungry-delete
    :defer 6
    :ensure t
    :diminish hungry-delete-mode
    :config
    (global-hungry-delete-mode))
#+END_SRC
* IEDIT
#+BEGIN_SRC emacs-lisp
  (use-package iedit
    :ensure t
    :bind
    ("M-%" . iedit-mode))
#+END_SRC
* LISPY
#+BEGIN_SRC emacs-lisp :tangle no
  (use-package lispy
    :disabled t
    :ensure t
    :defer t
    :hook
    (emacs-lisp-mode . lispy-mode)
    (lisp-mode . lispy-mode)
    (lisp-interaction-mode . lispy-mode))
#+END_SRC
* MARKDOWN

#+BEGIN_SRC emacs-lisp
  (use-package markdown-mode
    :ensure t
    :defer t
    :commands (markdown-mode gfm-mode)
    :mode (("README\\.md\\'" . gfm-mode)
           ("\\.md\\'" . markdown-mode)
           ("\\.markdown\\'" . markdown-mode))
    :init (setq markdown-command "multimarkdown"))
#+END_SRC

* PAREDIT
#+BEGIN_SRC emacs-lisp
  (use-package paredit
    :defer t
    :bind
    ("C-c t p" . paredit-mode))
#+END_SRC
* PC BUFFER SWITCH
#+BEGIN_SRC emacs-lisp
  (use-package pc-bufsw
    :if window-system
    :ensure t
    :bind
    ("C-<escape>" . pc-bufsw-mru)
    ("C-S-<escape>" . pc-bufsw-lru)
    :config
    (setq pc-bufsw-quit-time 1))
#+END_SRC
* POWERLINE
#+BEGIN_SRC emacs-lisp
  (use-package powerline
    :disabled
    :config
    (when (eq system-type 'darwin)
      (setq ns-use-srgb-colorspace nil))
    (powerline-default-theme))
#+END_SRC
* POWERSHELL
#+BEGIN_SRC emacs-lisp
  (use-package powershell
    :if (eq system-type 'windows-nt)
    :ensure t
    :mode "\\.ps1\\'")
#+END_SRC
* PROJECTILE

#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :ensure t
    :diminish projectile-mode
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :config
    (projectile-mode)
    (setq projectile-completion-system 'ivy)
    (when (require 'magit nil t)
      (mapc #'projectile-add-known-project
            (mapcar #'file-name-as-directory (magit-list-repos)))
      ;; Optionally write to persistent `projectile-known-projects-file'
      (projectile-save-known-projects)))
#+END_SRC

* PYTHON

[[https://emacs.stackexchange.com/questions/2745/make-fill-paragraph-in-python-docstring-leave-the-triple-quotes-on-separate-line/2758][Docstring Fill Column Mode]]

#+BEGIN_SRC emacs-lisp
  (use-package python-mode
    :ensure t
    :commands (python-mode)
    :mode (("\\.py\\'" . python-mode))
    :config
    (setq python-fill-docstring-style 'django))
#+END_SRC

https://realpython.com/emacs-the-best-python-editor/

** ELPY

https://elpy.readthedocs.io/en/latest/

#+BEGIN_SRC emacs-lisp
  (use-package elpy
    :ensure t
    :defer t
    :hook
    (python-mode . elpy-mode)
    :config
    (elpy-enable)
    (setq elpy-rpc-backend "jedi")
    (setq python-shell-interpreter "jupyter"
          python-shell-interpreter-args "console --simple-prompt"
          python-shell-prompt-detect-failure-warning nil)
    (add-to-list 'python-shell-completion-native-disabled-interpreters"jupyter"))
#+END_SRC

** PEP8

https://pypi.org/project/autopep8/

#+BEGIN_SRC emacs-lisp
  (use-package py-autopep8
    :ensure t
    :defer t
    :hook
    (python-mode . py-autopep8-enable-on-save))
#+END_SRC

** JEDI

https://github.com/anschwa/emacs.d#python

#+BEGIN_SRC emacs-lisp
  (use-package jedi
    :ensure t
    :defer t
    :init
    (setq jedi:complete-on-dot t)
    :hook
    (python-mode . jedi:setup))
#+END_SRC

** COMPANY JEDI

#+BEGIN_SRC emacs-lisp
  (use-package company-jedi
    :ensure t
    :defer t
    :config
    (add-to-list 'company-backends 'company-jedi))
#+END_SRC

* SMEX
#+BEGIN_SRC emacs-lisp
  (use-package smex
    :ensure t
    :defer t
    :after counsel)
#+END_SRC
* SSH-AGENCY
#+BEGIN_SRC emacs-lisp :tangle no
  (use-package ssh-agency
    :if (eq system-type 'windows-nt)
    :ensure t
    :defer t
    :init
    (setenv "SSH_ASKPASS" "git-gui--askpass"))
#+END_SRC
* WEB MODE
#+BEGIN_SRC emacs-lisp
  (use-package web-mode
    :ensure t
    :mode
    "\\.phtml\\'"
    "\\.tpl\\.php\\'"
    "\\.[agj]sp\\'"
    "\\.as[cp]x\\'"
    "\\.erb\\'"
    "\\.mustache\\'"
    "\\.djhtml\\'"
    "\\.html\\.twig\\'"
    "\\.html?\\'"
    "\\.php?\\'"
    "\\.css?\\'"
    :config
    (setq web-mode-markup-indent-offset 2)
    (setq web-mode-css-indent-offset 2)
    (setq web-mode-code-indent-offset 2)
    (setq web-mode-enable-auto-pairing t)
    (setq web-mode-enable-css-colorization t)
    (setq web-mode-enable-block-face t)
    (setq web-mode-enable-part-face t)
    (setq web-mode-enable-comment-keywords t))
#+END_SRC
* WGREP
#+BEGIN_SRC emacs-lisp
  (use-package wgrep
    :ensure t
    :defer t)
#+END_SRC
* WHICH KEY
#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :ensure t
    :defer t
    :diminish which-key-mode
    :init
    (which-key-mode))
#+END_SRC
* YASNIPPETS
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :ensure t
    :defer t
    :diminish yas-minor-mode
    :hook
    (prog-mode . yas-minor-mode)
    :config
    (use-package yasnippet-snippets
      :defer t
      :ensure t
      :after yasnippet))
#+END_SRC
