#+TITLE: EMACS BUILT IN PACKAGE CONFIGURATION
#+AUTHOR: Toby Slight

#+PROPERTY: header-args :cache yes
#+PROPERTY: header-args+ :mkdirp yes
#+PROPERTY: header-args+ :padline no
#+PROPERTY: header-args+ :results silent
#+PROPERTY: header-args+ :tangle ~/.emacs.d/site-lisp/my-packages-emacs.el
#+PROPERTY: header-args+ :tangle-mode (identity #o600)

#+OPTIONS: toc:t

Please see the [[file:README.org][README]] and/or [[file:my-tangles.org][my-tangles.org]] for instructions on how to
install.

This file contains configuration for built in Emacs packages, using
[[https://github.com/jwiegley][John Wiegley's]] amazing [[https://github.com/jwiegley/use-package][use-package]] macro.

* CONTENTS                                                         :TOC_5_gh:
- [[#abbrev-mode][ABBREV MODE]]
- [[#autofill][AUTOFILL]]
- [[#dired][DIRED]]
- [[#electric][ELECTRIC]]
- [[#erc][ERC]]
- [[#eldoc][ELDOC]]
- [[#eshell][ESHELL]]
- [[#flyspell][FLYSPELL]]
- [[#gnus][GNUS]]
- [[#linum-mode][LINUM MODE]]
- [[#lisp-mode][LISP MODE]]
- [[#misc][MISC]]
- [[#org][ORG]]
- [[#recentf][RECENTF]]
- [[#subword][SUBWORD]]
- [[#term][TERM]]
- [[#uniquify][UNIQUIFY]]
- [[#whitespace][WHITESPACE]]
- [[#winner-mode][WINNER MODE]]

* ABBREV MODE

#+BEGIN_QUOTE
Emacs has a nice feature to expand abbreviations. If for example, you
wanted an abbreviation for ‘Your Name’ to be ‘yn’, just type ‘yn’ and
with your point after the ‘n’ do C-x a i g (mnemonic add inverse
global) and enter the expansion, in this case ‘Your Name’. In the
future, whenever you type ‘yn’ your name will be inserted. The abbrevs
are automatically saved between sessions in a file ~/.abbrev_defs.

I find this most useful for fixing typos. Whenever you have a typo (I
type ‘becasue’ almost every time) if you are religious (see
alt.religion.emacs) and never correct it but instead do C-x a i g and
enter the correct spelling, emacs will fix all your typos, and you can
type like a reckless madman and emacs will clean up the mess behind
you. See AutoCorrection.

If you don’t like an abbrev that you have set up, then do M-x
edit-abbrevs. You can have different abbrevs for each mode (cperl,
c++, Message); the g in C-x a i g is for global, meaning every mode.

-- https://www.emacswiki.org/emacs/AbbrevMode
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (use-package abbrev
    :diminish abbrev-mode
    :defer t
    :hook
    (text-mode . abbrev-mode)
    :config
    (setq-default abbrev-mode t)
    (setq abbrev-file-name (concat user-emacs-directory "abbrevs"))
    (setq save-abbrevs 'silently))
#+END_SRC
* AUTOFILL

#+BEGIN_SRC emacs-lisp
  (use-package auto-fill-mode
    :bind
    ("C-c q" . auto-fill-mode)
    :hook
    text-mode
    org-mode)
#+END_SRC

* DIRED

#+BEGIN_SRC emacs-lisp
  (use-package dired
    :bind
    (:map
     dired-mode-map
     (")" .'dired-omit-mode)
     ("b" . (lambda () (interactive) (find-alternate-file "..")))
     ("c" . dired-do-compress)
     ("f" . dired-find-alternate-file)
     ("C-q" . kill-this-buffer)
     ("c" . dired-do-compress-to))
    :init
    (autoload 'dired-jump "dired-x" t)
    :config
    (when (eq system-type 'berkeley-unix)
      (progn
        (setq dired-listing-switches "-alhpL")))
    (setq dired-dwim-target t)
    (setq dired-use-ls-dired nil)
    (setq dired-omit-mode t)
    (setq dired-recursive-copies 'always)
    (setq dired-recursive-deletes 'always))
#+END_SRC

* ELECTRIC

#+BEGIN_QUOTE
Toggle on-the-fly reindentation (Electric Indent mode).  With a prefix
argument ARG, enable Electric Indent mode if ARG is positive, and
disable it otherwise.  If called from Lisp, enable the mode if ARG is
omitted or nil.

When enabled, this reindents whenever the hook
‘electric-indent-functions’ returns non-nil, or if you insert a
character from ‘electric-indent-chars’.

This is a global minor mode.  To toggle the mode in a single buffer,
use ‘electric-indent-local-mode’.

-- [[help:electric-indent-mode][Help Page]]
#+END_QUOTE

#+BEGIN_QUOTE
Toggle automatic parens pairing (Electric Pair mode).  With a prefix
argument ARG, enable Electric Pair mode if ARG is positive, and
disable it otherwise.  If called from Lisp, enable the mode if ARG is
omitted or nil.

Electric Pair mode is a global minor mode.  When enabled, typing an
open parenthesis automatically inserts the corresponding closing
parenthesis.  (Likewise for brackets, etc.). To toggle the mode in a
single buffer, use ‘electric-pair-local-mode’.

-- [[help:electric-pair-mode][Help Page]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (use-package electric
    :defer t
    :hook
    (prog-mode . electric-pair-mode)
    (prog-mode . electric-indent-mode)
    :config
    (electric-pair-mode 1)
    (electric-indent-mode 1))
#+END_SRC

* ERC
#+BEGIN_SRC emacs-lisp
  (use-package erc
    :defer t
    :config
    (setq erc-autojoin-channels-alist '(("freenode.net"
                                         "#org-mode"
                                         "#emacs")))
    (setq erc-fill-column 80)
    (setq erc-hide-list '("JOIN" "PART" "QUIT"))
    (setq erc-input-line-position -2)
    (setq erc-keywords '("not2b"))
    (setq erc-nick "not2b")
    (setq erc-prompt-for-password t)
    (setq erc-track-enable-keybindings t))
#+END_SRC
* ELDOC
#+BEGIN_SRC emacs-lisp
  (use-package eldoc
    :defer t
    :after lisp-mode
    :hook
    (lisp-mode . eldoc-mode)
    (lisp-interaction-mode . eldoc-mode)
    (emacs-lisp-mode . eldoc-mode))
#+END_SRC
* ESHELL

[[https://www.masteringemacs.org/article/complete-guide-mastering-eshell][Mastering Eshell]]

[[https://github.com/bling/dotemacs/blob/master/config/init-eshell.el][Eshell Config]]

[[http://www.howardism.org/Technical/Emacs/eshell-fun.html][Howardism Eshell]]

[[https://github.com/magnars/.emacs.d/blob/master/settings/setup-shell.el][Magnars Shell Setup]]

#+BEGIN_SRC emacs-lisp
  (use-package eshell
    :defer t
    :bind
    ("C-c a s" . eshell)
    :config
    (use-package em-smart)
    (setq eshell-history-size 1024)
    (setq eshell-where-to-jump 'begin)
    (setq eshell-review-quick-commands nil)
    (setq eshell-smart-space-goes-to-end t))
#+END_SRC
* FLYSPELL
#+BEGIN_SRC emacs-lisp
  (use-package flyspell
    :defer t
    :diminish flyspell-mode
    :hook
    (text-mode . flyspell-mode)
    (org-mode . flyspell-mode)
    (prog-mode . flyspell-prog-mode)
    :config
    (when (eq system-type 'darwin) ;; mac specific settings
      (setq ispell-program-name "/usr/local/bin/ispell")))
#+END_SRC
* GNUS
#+BEGIN_SRC emacs-lisp
  (use-package gnus
    :defer t
    :config
    (setq gnus-init-file "~/.emacs.d/init.el")
    (setq gnus-home-directory "~/.emacs.d/")
    (setq gnus-completing-read-function 'gnus-ido-completing-read)
    (use-package nnir)
    (setq message-directory "~/.emacs.d/mail")
    (setq gnus-directory "~/.emacs.d/news")
    (setq nnfolder-directory "~/.emacs.d/mail/archive")
    (setq gnus-use-full-window nil)
    (setq gnus-select-method '(nntp "news.gnus.org"))
    (setq gnus-summary-thread-gathering-function
          'gnus-gather-threads-by-subject)
    (setq gnus-thread-hide-subtree t)
    (setq gnus-thread-ignore-subject t))
#+END_SRC
* LINUM MODE
#+BEGIN_SRC emacs-lisp
  (use-package linum
    :defer t
    :hook
    (prog-mode . linum-mode)
    (shell-script-mode . linum-mode)
    (sh-mode . linum-mode))
#+END_SRC
* LISP MODE
#+BEGIN_SRC emacs-lisp
  (use-package lisp-mode
    :defer t
    :hook ((emacs-lisp-mode lisp-mode)
           . (lambda ()
               (add-hook 'after-save-hook 'check-parens nil t))))
#+END_SRC
* MISC
#+BEGIN_SRC emacs-lisp
  (use-package misc
    :bind
    ("C-z" . zap-up-to-char)
    ("M-z" . zap-to-char))
#+END_SRC
* ORG

Attempt to get org-mode to allow emphasis across multiple lines when
auto-fill is turned on.

*Two different ways to do the same thing:*

https://emacs.stackexchange.com/questions/18101/org-mode-multi-line-emphasis-and-bold
https://emacs.stackexchange.com/questions/27892/italic-paragraphs-in-org-mode

I then found out from [[https://lists.gnu.org/archive/html/emacs-orgmode/2013-03/msg01172.html][this]] mailing list thread that:

*We need to set this variable BEFORE we load org* via use-package in
[[file:packages.org::*ORG][the org section of packages.org]]

#+BEGIN_QUOTE
This should probably happen before org is loaded, according to the
docstring.

> Mebbe I just forgot some setting to get it working, though I'd like the
> exporter to recognize the org-emphasis-regexp-components settings...

The exporter relies on the parser, which relies on `org-emph-re', which
is built from `org-emphasis-regexp-components'.
#+END_QUOTE

I don't like how org-mode inserts a new line before and after each
heading when a file is tangled.

#+BEGIN_QUOTE
The default value is '((heading . auto) (plain-list-item . auto)), so
it normally will insert a newline before a heading (the auto part in
the heading). You can specify Never when you customize the variable,
and it will not insert a newline.

-- [[https://stackoverflow.com/questions/28351465/emacs-orgmode-do-not-insert-line-between-headers][Stackexchange Question]]
#+END_QUOTE

[[file:my-org.org][Org Configuration File]]

#+BEGIN_SRC emacs-lisp
  (use-package org
    :diminish
    :bind
    ("C-c o l" . org-store-link)
    :mode ("\\.org\\'" . org-mode)
    :init
    (setf org-blank-before-new-entry '((heading . nil) (plain-list-item . nil)))
    (setq org-emphasis-regexp-components '(" \t('\"{" "- \t.,:!?;'\")}\\" " \t\r\n,\"'" "." 300))
    :config
    (setq org-confirm-babel-evaluate t)
    (setq org-agenda-files (file-expand-wildcards "~/*.org"))
    (setq org-agenda-files (quote ("~/org/todo.org")))
    (setq org-default-notes-file "~/org/notes.org")
    (setq org-directory "~/org")
    (setq org-export-with-toc t)
    (setq org-completion-use-ido t)
    (setq org-indent-indentation-per-level 1)
    (setq org-list-allow-alphabetical t)
    (setq org-list-indent-offset 1)
    ;; (setq org-replace-disputed-keys t) ;; fix windmove conflicts
    (setq org-return-follows-link t)
    (setq org-refile-use-outline-path 'file)
    (setq org-outline-path-complete-in-steps nil)
    (setq org-refile-allow-creating-parent-nodes 'confirm)
    (setq org-refile-targets '((nil :maxlevel . 9)))
    (setq org-speed-commands-user (quote (("N" . org-down-element)
                                          ("P" . org-up-element))))
    (setq org-src-fontify-natively t)
    (setq org-src-tab-acts-natively t)
    (setq org-src-window-setup 'current-window)
    (setq org-startup-indented t)
    (setq org-use-fast-todo-selection t)
    (setq org-use-speed-commands t))
#+END_SRC
* RECENTF

[[https://www.reddit.com/r/emacs/comments/3g468d/stop_recent_files_showing_elpa_packages/][Stop Recent Files showing elpa packages?]]

[[https://regexr.com/][RegEx WebApp]]

#+BEGIN_SRC emacs-lisp
  (use-package recentf
    :bind
    ("<f12>" . recentf-open-files)
    :config
    (recentf-mode 1)
    (setq recentf-exclude '(".*init\.el"
                            ".*\/my-.*\.el"
                            "^/var/folders\\.*"
                            "COMMIT_EDITMSG\\'"
                            ".*-autoloads\\.el\\'"
                            "[/\\]\\.elpa/"))
    (setq recentf-max-menu-items 128)
    (setq recentf-max-saved-items 256))
#+END_SRC

* SUBWORD
#+BEGIN_SRC emacs-lisp
  (use-package subword
    :defer 4
    :diminish subword-mode
    :config
    (global-subword-mode 1))
#+END_SRC
* TERM

[[https://stackoverflow.com/questions/9983731/emacs-and-ansi-term-elisp-iterate-through-a-list-of-buffers][StackOverflow Term Cycle]]

[[http://www.enigmacurry.com/2008/12/26/emacs-ansi-term-tricks/][Ansi Term Tricks]]

[[https://www.reddit.com/r/emacs/comments/46l1mu/how_to_make_ansiterm_go_to_the_same_buffer/][Switch to ansi-term]]

#+BEGIN_SRC emacs-lisp
  (use-package term
    :defer t
    :config
    (setq term-buffer-maximum-size 200000)
    (defadvice term-handle-exit
        (after term-kill-buffer-on-exit activate)
      (kill-buffer)))
#+END_SRC
* UNIQUIFY
#+BEGIN_SRC emacs-lisp

  (use-package uniquify
    :defer t
    :config
    (setq uniquify-buffer-name-style 'forward))
#+END_SRC

* WHITESPACE
#+BEGIN_SRC emacs-lisp
  (add-hook 'before-save-hook 'whitespace-cleanup)
#+END_SRC
* WINNER MODE
#+BEGIN_SRC emacs-lisp
  (use-package winner
    :bind
    ("C-c C-/" . winner-undo)
    ("C-c C-?" . winner-redo)
    :config
    (winner-mode t))
#+END_SRC
